[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
blur = true
resize_increments = true
opacity = 0.84
decorations = "None"

[window.padding]
x = 5
y = 5

[font]
size = 12.0

[font.bold]
family = "CommitMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CommitMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CommitMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CommitMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0



